In [5]:
import pandas as pd

In [6]:
csv_file = "cscpopendata.csv"
cosmeticData_df = pd.read_csv(csv_file)
cosmeticData_df.head()

,CDPHId,ProductName,CSFId,CSF,CompanyId,CompanyName,BrandName,PrimaryCategoryId,PrimaryCategory,SubCategoryId,...,CasNumber,ChemicalId,ChemicalName,InitialDateReported,MostRecentDateReported,DiscontinuedDate,ChemicalCreatedAt,ChemicalUpdatedAt,ChemicalDateRemoved,ChemicalCount
0,2,ULTRA COLOR RICH EXTRA PLUMP LIPSTICK-ALL SHADES,NaN,NaN,4,New Avon LLC,AVON,44,Makeup Products (non-permanent),53,...,13463-67-7,6,Titanium dioxide,06/17/2009,08/28/2013,02/01/2011,07/09/2009,07/09/2009,NaN,1
1,3,Glover's Medicated Shampoo,NaN,NaN,338,J. Strickland & Co.,Glover's,18,Hair Care Products (non-coloring),25,...,65996-92-1,4,Distillates (coal tar),07/01/2009,07/01/2009,NaN,07/01/2009,07/01/2009,NaN,2
2,3,Glover's Medicated Shampoo,NaN,NaN,338,J. Strickland & Co.,Glover's,18,Hair Care Products (non-coloring),25,...,140-67-0,5,Estragole,07/01/2009,07/01/2009,NaN,07/02/2009,07/02/2009,NaN,2
3,4,PRECISION GLIMMER EYE LINER-ALL SHADES �,NaN,NaN,4,New Avon LLC,AVON,44,Makeup Products (non-permanent),46,...,13463-67-7,7,Titanium dioxide,07/09/2009,08/28/2013,NaN,07/09/2009,07/09/2009,NaN,1
4,5,AVON BRILLIANT SHINE LIP GLOSS-ALL SHADES �,NaN,NaN,4,New Avon LLC,AVON,44,Makeup Products (non-permanent),52,...,13463-67-7,8,Titanium dioxide,07/09/2009,08/28/2013,02/01/2011,07/09/2009,07/09/2009,NaN,1

In [7]:
cosmeticData_df = cosmeticData_df.dropna(subset=['DiscontinuedDate'])
cosmeticData_df.head()

,CDPHId,ProductName,CSFId,CSF,CompanyId,CompanyName,BrandName,PrimaryCategoryId,PrimaryCategory,SubCategoryId,...,CasNumber,ChemicalId,ChemicalName,InitialDateReported,MostRecentDateReported,DiscontinuedDate,ChemicalCreatedAt,ChemicalUpdatedAt,ChemicalDateRemoved,ChemicalCount
0,2,ULTRA COLOR RICH EXTRA PLUMP LIPSTICK-ALL SHADES,NaN,NaN,4,New Avon LLC,AVON,44,Makeup Products (non-permanent),53,...,13463-67-7,6,Titanium dioxide,06/17/2009,08/28/2013,02/01/2011,07/09/2009,07/09/2009,NaN,1
4,5,AVON BRILLIANT SHINE LIP GLOSS-ALL SHADES �,NaN,NaN,4,New Avon LLC,AVON,44,Makeup Products (non-permanent),52,...,13463-67-7,8,Titanium dioxide,07/09/2009,08/28/2013,02/01/2011,07/09/2009,07/09/2009,NaN,1
5,6,JILLIAN DEMPSEY FOR AVON CELESTIAL EYESHADOW-A...,NaN,NaN,4,New Avon LLC,AVON,44,Makeup Products (non-permanent),48,...,13463-67-7,9,Titanium dioxide,07/09/2009,08/28/2013,11/01/2010,07/09/2009,07/09/2009,NaN,1
30,18,SPECTRA LASH MASCARA �,NaN,NaN,4,New Avon LLC,AVON,44,Makeup Products (non-permanent),162,...,13463-67-7,24,Titanium dioxide,07/20/2009,08/28/2013,02/01/2012,07/20/2009,07/20/2009,NaN,1
381,222,ANEW EYELIFTING SERUM SHADOW-ALL SHADES �,NaN,NaN,4,New Avon LLC,ANEW,44,Makeup Products (non-permanent),48,...,13463-67-7,235,Titanium dioxide,09/01/2009,08/28/2013,11/01/2012,09/01/2009,09/01/2009,NaN,2

In [8]:
# cosmeticData_df['Counts'] = cosmeticData_df.groupby(['CompanyName'])['DiscontinuedDate'].transform('count')
# cosmeticData_df.head()

cosmeticData_df = cosmeticData_df.groupby('CompanyName').agg({'DiscontinuedDate':','.join, 'ChemicalName': ', '.join, 'DiscontinuedDate':"count"}).reset_index()
cosmeticData_df.head()

,CompanyName,DiscontinuedDate,ChemicalName
0,AFFLINK,8,"Cocamide diethanolamine, Cocamide diethanolami..."
1,AMCO International,43,"Titanium dioxide, Titanium dioxide, Titanium d..."
2,"APLICARE, INC",22,"Diethanolamine, Formaldehyde (gas), Cocamide d..."
3,Added Extras LLC,3,"Ethyl acrylate, Ethyl acrylate, Ethyl acrylate"
4,"Alberto Culver USA, Inc.",4,"Titanium dioxide, Titanium dioxide, Titanium d..."

In [9]:
cosmeticData_df = cosmeticData_df.sort_values(by='DiscontinuedDate', ascending=False)
cosmeticData_df.head()

,CompanyName,DiscontinuedDate,ChemicalName
160,The Procter & Gamble Company,2856,"Titanium dioxide, Titanium dioxide, Titanium d..."
171,Victoria's Secret Beauty,1176,"Titanium dioxide, Titanium dioxide, Titanium d..."
50,"Elizabeth Arden, Inc.",743,"Titanium dioxide, Retinol/retinyl esters, when..."
91,MAESA LLC,643,"Mineral oils, untreated and mildly treated, Mi..."
15,Bath & Body Works,563,"Titanium dioxide, Titanium dioxide, Titanium d..."

In [12]:
cosmeticData_df.to_csv("All_Companies_Ascending_DD.csv")

In [39]:
# import difflib
# difflib.get_close_matches

# # companies = ['Procter','Shiseido','Johnson','LVMH','L Brands','Avon','Henkel','Colgate','Revlon']

# Company_data = cosmeticData_df.loc[cosmeticData_df.where(cosmeticData_df['CompanyName'],'Procter')]
# Company_data

In [40]:
# companies = ['Procter','Shiseido','Johnson','LVMH','L Brands','Avon','Henkel','Colgate','Revlon']
# Stock_Company_Data = []

# for company in companies:
#     if companies in cosmeticData_df:
#         Stock_Company_Data.append()

# Stock_Company_Data